//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int CodigoBarra { get; set; }
        public string Nombre { get; set; }
        public string Familia { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> DescuentoTope { get; set; }
        public string Descripcion { get; set; }
    }
}
